version: "3.9"

services:
  app:
    build: .
    container_name: ai-interviewer-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
     
      PORT: ${PORT:-3000}
      MONGO_URI: ${MONGO_URI:-mongodb://mongo:27017/ai_interviewer}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      NODE_ENV: ${NODE_ENV:-production}
      JWT_SECRET: ${JWT_SECRET:-change_this_in_prod}
      ADMIN_SECRET_CODE: ${ADMIN_SECRET_CODE:-change_this_in_prod}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
      EMAIL_USER: ${EMAIL_USER:-}
      EMAIL_PASS: ${EMAIL_PASS:-}
      CONTENT_SERVER_FLASK: ${CONTENT_SERVER_FLASK:-http://localhost:5009}
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand(\"ping\").ok' | grep 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  mongo_data:
