name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Prepare SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          printf "%s" "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          printf "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Pull & restart on server
        env:
          REGISTRY: ghcr.io
          IMAGE: ghcr.io/${{ github.repository }}:latest
          HOST: ${{ secrets.DEPLOY_HOST }}
          USER: ${{ secrets.DEPLOY_USER }}
          APP_DIR: ${{ secrets.DEPLOY_APP_DIR }} 
          ENV_FILE: ${{ secrets.DEPLOY_ENV_FILE }} 
        run: |
          ssh ${USER}@${HOST} << 'EOF'
          set -e
          mkdir -p ${APP_DIR}
          cd ${APP_DIR}

          # login to GHCR (if needed) using a PAT stored on the server or pre-configured)
          # echo $GHCR_PAT | docker login ghcr.io -u USERNAME --password-stdin

          docker pull ${IMAGE} || true

          # stop and remove existing container
          docker rm -f ai-interviewer || true

          # run with env file and volume for uploads
          docker run -d \
            --name ai-interviewer \
            --restart unless-stopped \
            --env-file ${ENV_FILE} \
            -p 3000:3000 \
            -v ${APP_DIR}/uploads:/app/uploads \
            ${IMAGE}
          EOF
